name: Deploy to Lamp Server

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to server via SSH
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: lamp.ms.wits.ac.za
        username: sdevsoc
        password: ${{ secrets.SSH_PASSWORD }}  # Store the password in GitHub Secrets
        script: |
          cd public_html/devsoc-website
          git pull
          
